apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: inosis-vault
  annotations:
    iam.gke.io/gcp-service-account: vault-terraform-admin@project-0497ef4c-ab4c-42b5-96c.iam.gserviceaccount.com
